# Generated by Django 6.0.5 on 2026-05-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_rename_book_id_borrowing_book_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payments",
            new_name="Payment",
        ),
    ]
